### ISSUE TITLE
No pokeballs of type cause item count field to be missing

### ISSUE THREAD

**Issue by dbmurphy** [OpenPoGo/OpenPoGoBot#106]
### Expected Behavior

If a user has no pokeball of a type such as great balls, it should report 0.
### Actual Behavior

The code will fault on the 'count' key missing as the item_id is present but not count with no inventory.
### Steps to Reproduce

Log into the app trash all balls of a type 
Start app when it tries to count the balls it will get:

```
Traceback (most recent call last):
  File "pokecli.py", line 242, in <module>
    main()
  File "pokecli.py", line 230, in main
    bot.start()
  File "/Users/dmurphy/Desktop/PokeGo/dbmurphy-OpenPoGoBot/pokemongo_bot/__init__.py", line 55, in start
    self._setup_api()
  File "/Users/dmurphy/Desktop/PokeGo/dbmurphy-OpenPoGoBot/pokemongo_bot/__init__.py", line 225, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/Users/dmurphy/Desktop/PokeGo/dbmurphy-OpenPoGoBot/pokemongo_bot/__init__.py", line 307, in pokeball_inventory
    item_count = int(item_data['count'])
KeyError: 'count'
```

This can be corrected by adding a check for the key just prior to using it.
### Other Information

OS:  OSX
Git Commit: d1304935d33f969a651522d1a130f41ecb39b97f

**Comment by pokemon-masterbater** [comment]
Having the same issue

**Comment by dbmurphy** [comment]
You can use my branch to fix it it's a pretty minor patch if you just want to apply the patch for now.

**Comment by JulianMBr** [comment]
This should be fixed within the latest version.
