### ISSUE TITLE
crash after startup

### ISSUE THREAD

**Issue by MathieuVachon** [OpenPoGo/OpenPoGoBot#109]
Please see stack trace:

[2016-07-29 03:08:21] [#] -- Level: 12
[2016-07-29 03:08:21] [#] -- Experience: 70360
[2016-07-29 03:08:21] [#] -- Experience until next level: 4640
[2016-07-29 03:08:21] [#] -- Pokemon Captured: 177
[2016-07-29 03:08:21] [#] -- Pokestops Visited: 143
[2016-07-29 03:08:21] [x] Initial Transfer.
[2016-07-29 03:08:21] [x] Will NOT transfer anything above CP 500 or these ['']
Traceback (most recent call last):
  File "./pokecli.py", line 240, in <module>
    main()
  File "./pokecli.py", line 228, in main
    bot.start()
  File "/root/OpenPoGoBot/pokemongo_bot/**init**.py", line 55, in start
    self._setup_api()
  File "/root/OpenPoGoBot/pokemongo_bot/__init__.py", line 250, in _setup_api
    worker.work()
  File "/root/OpenPoGoBot/pokemongo_bot/cell_workers/initial_transfer_worker.py", line 23, in work
    pokemon_groups = self._initial_transfer_get_groups()
  File "/root/OpenPoGoBot/pokemongo_bot/cell_workers/initial_transfer_worker.py", line 57, in _initial_transfer_get_groups
    inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'

**Comment by epicblood** [comment]
been seeing this issue all day, seems to be random. Just try to restart a few times and it'l work work eventually.

**Comment by dbmurphy** [comment]
Sometimes the payload is not being returned by the API. I have been looking at this issue as it's system everywhere the API is used, we should get these error and respond in a better way to  sleep then reconnect IMHO.

**Comment by wchill** [comment]
This error should be fixed in #112, please test that branch.

**Comment by wchill** [comment]
Closed by #112.
