### ISSUE TITLE
pull on master, import issue

### ISSUE THREAD

**Issue by MathieuVachon** [OpenPoGo/OpenPoGoBot#120]
Hi there,

After pulling latest from main I get :

Traceback (most recent call last):
  File "./pokecli.py", line 37, in <module>
    from pokemongo_bot import logger
  File "/root/OpenPoGoBot/pokemongo_bot/**init**.py", line 14, in <module>
    from pokemongo_bot import logger, cell_workers, human_behaviour, item_list, stepper
  File "/root/OpenPoGoBot/pokemongo_bot/cell_workers/**init**.py", line 4, in <module>
    from pokemongo_bot.cell_workers.seen_fort_worker import SeenFortWorker
  File "/root/OpenPoGoBot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 7, in <module>
    from pokemongo_bot.utils import format_time, f2i
  File "/root/OpenPoGoBot/pokemongo_bot/utils.py", line 10, in <module>
    from api.worldmap import PokeStop
  File "/root/OpenPoGoBot/api/**init**.py", line 6, in <module>
    from pgoapi.exceptions import ServerSideRequestThrottlingException  # type: ignore
ImportError: cannot import name ServerSideRequestThrottlingException

**Comment by wchill** [comment]
Please `pip install --upgrade -r requirements.txt`.

**Comment by MathieuVachon** [comment]
excellent, fixed. thx.
