### ISSUE TITLE
Map isn't working can anyone help.

### ISSUE THREAD

**Issue by Rlewisrlou666** [OpenPoGo/OpenPoGoBot#123]
### Dropping me in Luxembourg City but the logs are still working but not auto scrolling.

also getting these errors in Terminal.

![snip20160730_6](https://cloud.githubusercontent.com/assets/20677921/17273063/1dc99c52-56a0-11e6-8ea4-ad31529e506f.png)
### Run OpenPoGoBot from folder using

python2 pokecli.py -a ptc -u USER -p PASS --location "51.640513, -2.678127"

**Comment by pokemon-masterbater** [comment]
I've noticed it is no longer writing data to the .json files in the web folder

**Comment by Rlewisrlou666** [comment]
Still not working for me is there still an issue?

**Comment by wchill** [comment]
Broken pipe is fine (it just means that your browser disconnected from the web server).

All other web stuff except logging is currently nonfunctional since the old code crashed Python 3.5 due to the use of byte strings from API responses. This will be fixed ASAP.

**Comment by TaciteOFF** [comment]
Had the same kind of error when I closed my browser.

```
[2016-07-31 18:23:18] [#] Walking from (50.6376086, 3.0689158) to (50.6379282, 3.0680208) for approx. 58.00 seconds
[2016-07-31 18:23:28] Web client connected
[2016-07-31 18:24:32] [#] Walking from (50.6379282, 3.0680208) to (50.6377464, 3.067708) for approx. 24.00 seconds
Exception in thread Thread-121:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by wchill** [comment]
Yes, I will look into finding a way to hide that error since it's not really an error.
