### ISSUE TITLE
Catching Pokemon crash

### ISSUE THREAD

**Issue by pokemon-masterbater** [OpenPoGo/OpenPoGoBot#137]
When catching a Pokemon I am getting the following:

---

[2016-07-31 14:00:48] [Catch] A wild Rhyhorn appeared! [CP 240] [Potential 0.53]
[2016-07-31 14:00:52] [Catch] Ultra Ball stock is low... saving for pokemon with cp greater than 700
Traceback (most recent call last):
  File "pokecli.py", line 260, in <module>
    main()
  File "pokecli.py", line 253, in main
    bot.take_step()
  File "/home/frank/pokemongo_bot/**init**.py", line 74, in take_step
    self.stepper.take_step()
  File "/home/frank/pokemongo_bot/stepper.py", line 41, in take_step
    self._work_at_position(position[0], position[1], True)
  File "/home/frank/pokemongo_bot/stepper.py", line 137, in _work_at_position
    self.bot.work_on_cell(cell, pokemon_only)
  File "/home/frank/pokemongo_bot/__init__.py", line 79, in work_on_cell
    self.fire("pokemon_found", encounters=cell.catchable_pokemon + cell.wild_pokemon)
  File "/home/frank/pokemongo_bot/**init**.py", line 71, in fire
    manager.fire_with_context(event, self, _args, *_kwargs)
  File "/home/frank/pokemongo_bot/event_manager.py", line 107, in fire_with_context
    return self.fire(event_name, _args, *_kwargs)
  File "/home/frank/pokemongo_bot/event_manager.py", line 101, in fire
    return self.events[event_name].fire(_args, *_kwargs)
  File "/home/frank/pokemongo_bot/event_manager.py", line 64, in fire
    return_dict = listener(**listener_args)
  File "./plugins/catch_pokemon/**init**.py", line 89, in pokemon_found
    balls_stock[pokeball] -= 1
KeyError: 0

**Comment by wchill** [comment]
Fix incoming.

**Comment by wchill** [comment]
As a temporary fix until the relevant code is patched, find this code and modify it: https://github.com/OpenPoGo/OpenPoGoBot/blob/master/plugins/catch_pokemon/__init__.py#L83

It should be "if total_pokeballs == 0 or pokeball == 0:"

**Comment by pokemon-masterbater** [comment]
Thank you, also are all Pokemon exchanged for candy now? I don't see the IV being used after catching

**Comment by pokemon-masterbater** [comment]
Now I am getting

  File "./plugins/catch_pokemon/**init**.py", line 56, in pokemon_found
    if total_pokeballs == 0 or pokeball == 0:
UnboundLocalError: local variable 'pokeball' referenced before assignment

**Comment by wchill** [comment]
You changed the wrong line. There are two places where that code appears; change the second one.

**Comment by wchill** [comment]
Pokemonnare only exchanges for candy when the bag is full, the way the bot is set up right now.
