### ISSUE TITLE
Error After Commit #125 (Egg Hatching)

### ISSUE THREAD

**Issue by yusufRahmatullah** [OpenPoGo/OpenPoGoBot#139]
### Expected Behavior

normal as usual
### Actual Behavior

I Got this error after pull new commit
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pokemongo_bot import logger
  File "D:\games\OpenPoGoBot\pokemongo_bot__init__.py", line 14, in <module>
    from pokemongo_bot import logger, cell_workers, human_behaviour, item_list, stepper
  File "D:\games\OpenPoGoBot\pokemongo_bot\cell_workers__init__.py", line 3, in <module>
    from pokemongo_bot.cell_workers.walk_towards_fort_worker import WalkTowardsFortWorker
  File "D:\games\OpenPoGoBot\pokemongo_bot\cell_workers\walk_towards_fort_worker.py", line 5, in <module>
    from pokemongo_bot.utils import distance, format_dist
  File "D:\games\OpenPoGoBot\pokemongo_bot\utils.py", line 10, in <module>
    from api.worldmap import PokeStop
  File "D:\games\OpenPoGoBot\api__init__.py", line 6, in <module>
    from pgoapi.exceptions import ServerSideRequestThrottlingException  # type: ignore
ImportError: cannot import name ServerSideRequestThrottlingException
### Other Information

OS: Windows 8.1
Git Commit:

**Comment by MaxLeiter** [comment]
Can't duplicate here: have you tried `pip install -r requirements.txt` and updating the submodule? (`git submodule update`)?

**Comment by 1karu5** [comment]
#122
