### ISSUE TITLE
Unicode Errors (System specific)

### ISSUE THREAD

**Issue by 1karu5** [OpenPoGo/OpenPoGoBot#173]
### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 347, in <module>
    main()
  File "pokecli.py", line 340, in main
    bot.run()
  File "OpenPoGoBot/pokemongo_bot/**init**.py", line 92, in run
    self.navigator.navigate(map_cells)
  File "OpenPoGoBot/pokemongo_bot/navigation/fort_navigator.py", line 40, in navigate
    logger.log("[#] Walking towards PokeStop \"{}\" ({} away)".format(fort_name, format_dist(dist, unit)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe2' in position 24: ordinal not in range(128)
### Other Information

OS: debian
Git Commit: 7df83ac094901222febaf5c34620e86b3dd34ffa

**Comment by lazyfai** [comment]
For non-unicode fort name, we need either use u'{}' or add an import in the source of affected files:
from **future** import unicode_literals
This make the format function works well for me (I am in Hong Kong)

Source:
http://stackoverflow.com/questions/3235386/python-using-format-on-a-unicode-escaped-string

**Comment by web0net** [comment]
The same problem 

[2016-08-02 09:47:44] [x] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "pokecli.py", line 347, in <module>
    main()
  File "pokecli.py", line 340, in main
    bot.run()
  File "/home/poke/pokemongo_bot/**init**.py", line 91, in run
    self.work_on_cells(map_cells)
  File "/home/poke/pokemongo_bot/**init**.py", line 98, in work_on_cells
    self.fire("pokestops_found", pokestops=cell.pokestops)
  File "/home/poke/pokemongo_bot/**init**.py", line 85, in fire
    manager.fire_with_context(event, self, _args, *_kwargs)
  File "/home/poke/pokemongo_bot/event_manager.py", line 107, in fire_with_context
    return self.fire(event_name, _args, *_kwargs)
  File "/home/poke/pokemongo_bot/event_manager.py", line 101, in fire
    return self.events[event_name].fire(_args, *_kwargs)
  File "/home/poke/pokemongo_bot/event_manager.py", line 64, in fire
    return_dict = listener(**listener_args)
  File "./plugins/spin_pokestop/**init**.py", line 45, in visit_near_pokestops
    manager.fire_with_context('pokestop_arrived', bot, pokestop=pokestop)
  File "/home/poke/pokemongo_bot/event_manager.py", line 107, in fire_with_context
    return self.fire(event_name, _args, *_kwargs)
  File "/home/poke/pokemongo_bot/event_manager.py", line 101, in fire
    return self.events[event_name].fire(_args, *_kwargs)
  File "/home/poke/pokemongo_bot/event_manager.py", line 64, in fire
    return_dict = listener(**listener_args)
  File "./plugins/spin_pokestop/**init**.py", line 72, in spin_pokestop
    format_dist(dist, bot.config.distance_unit)), color="yellow")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)

**Comment by Reaver01** [comment]
please test https://github.com/OpenPoGo/OpenPoGoBot/pull/159

**Comment by lazyfai** [comment]
Adding "from future import unicode_literals" seems a good workaround.

**Comment by Reaver01** [comment]
@lazyfai I will test that when I get home.

**Comment by Reaver01** [comment]
please test https://github.com/OpenPoGo/OpenPoGoBot/pull/177

**Comment by Gnacik** [comment]
Got one pokestop which break bot all the time, with #177 working without any problems.

**Comment by Reaver01** [comment]
I get a travis CI build error. not sure about it.  
Fixed.

**Comment by 1karu5** [comment]
@Gnacik i think ec5b155d6d10047a5d06a9394012fc3017d5787f was working fine...could you verify this with your "one pokestop which break bot all the time" ?

**Comment by Gnacik** [comment]
After ec5b155 i've got crash every time when i go to that pokestop, it have some italian chars.

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 3: ordinal not in range(128)
```

with #177 problem disappear.

**Comment by 1karu5** [comment]
okay
yes, #177 will fix it

**Comment by GucciChen** [comment]
@Reaver01  hellow ，i have another problem. i want to use proxy then have one error. May you help me .
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1751b7e090>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by 1karu5** [comment]
@GucciChen it has nothing to do with our bot or even this ticket here...
