### ISSUE TITLE
'Your request was denied.' geopy.exc.GeocoderQueryError: Your request was denied.

### ISSUE THREAD

**Issue by trilips** [OpenPoGo/OpenPoGoBot#190]
### Expected Behavior

Login
### Actual Behavior

$ python pokecli.py -j "config.json"
[2016-08-03 01:28:39] [x] PokemonGO Bot v1.0
[2016-08-03 01:28:39] [x] Configuration initialized
[2016-08-03 01:28:39] [Plugins] Loaded plugin "web".
[2016-08-03 01:28:39] [Plugins] Loaded plugin "recycle_items".
[2016-08-03 01:28:39] [Plugins] Loaded plugin "catch_pokemon".
[2016-08-03 01:28:39] [Plugins] Loaded plugin "spin_pokestop".
[2016-08-03 01:28:39] [Plugins] Loaded plugin "transfer_pokemon".
[2016-08-03 01:28:39] [Plugins] Loaded plugin "egg_incubator".
[2016-08-03 01:28:42] [Plugins] Plugins loaded: ['catch_pokemon', 'egg_incubator', 'recycle_items', 'spin_pokestop', 'transfer_pokemon', 'web']
[2016-08-03 01:28:42] [Events] Events available: ['incubate_egg', 'item_bag_full', 'logging', 'pokemon_bag_full', 'pokemon_found', 'pokestop_arrived', 'pokestops_found', 'position_updated', 'set_campsite', 'transfer_pokemon', 'walking_started', 'waypoint_add', 'waypoint_remove']
[2016-08-03 01:28:42] [x] Fetching altitude from google
[2016-08-03 01:28:42] [x] Could not fetch altitude from google. Trying geolocator.
Traceback (most recent call last):
  File "pokecli.py", line 347, in <module>
    main()
  File "pokecli.py", line 335, in main
    bot.start()
  File "/home/x/openpogobot/pokemongo_bot/**init**.py", line 70, in start
    self._setup_api()
  File "/home/x/openpogobot/pokemongo_bot/__init__.py", line 145, in _setup_api
    self._set_starting_position()
  File "/home/x/openpogobot/pokemongo_bot/__init__.py", line 249, in _set_starting_position
    self._read_config_location()
  File "/home/x/openpogobot/pokemongo_bot/__init__.py", line 255, in _read_config_location
    self.position = self._get_pos_by_name(self.config.location)
  File "/home/x/openpogobot/pokemongo_bot/__init__.py", line 285, in _get_pos_by_name
    loc = geolocator.geocode(location_name, timeout=10)
  File "/home/x/openpogobot/env/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/home/x/openpogobot/env/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 338, in _parse_json
    self._check_status(page.get('status'))
  File "/home/x/openpogobot/env/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 369, in _check_status
    'Your request was denied.'
geopy.exc.GeocoderQueryError: Your request was denied.
### Steps to Reproduce

everything
### Other Information

OS: ubuntu 16.14 LTS

**Comment by wchill** [comment]
Use a Google Maps API key.

**Comment by trilips** [comment]
I have a google maps API browser key

**Comment by wchill** [comment]
are all Google Maps services enabled for that API key in the Google dashboard?

**Comment by lazyfai** [comment]
You need to enable at least the navigation and geocoder APIs

**Comment by trilips** [comment]
i have these enabled:
 Google Maps Geocoding API  
 Google Maps Directions API 
 Google Maps Distance Matrix API  
 Google Maps Elevation API  
 Google Maps Geolocation API  
 Google Maps Roads API  
 Google Places API Web Service  
 Google Static Maps API 
 Google Street View Image API

**Comment by plgonzalezrx8** [comment]
You need to enable all the Google Maps APIs

**Comment by trilips** [comment]
disabled them all, re-enabled them all
Issue fixed thank you
