### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by umanghome** [OpenPoGo/OpenPoGoBot#217]
### Expected Behavior

Bot should start
### Actual Behavior

AttributeError is being thrown
### Steps to Reproduce

??
### Other Information

OS: OS X
Git Commit: 

I am getting this error as soon as I run "python pokecli.py --config config.json"

Traceback (most recent call last):
  File "pokecli.py", line 361, in <module>
    main()
  File "pokecli.py", line 349, in main
    bot.start()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/pokemongo_bot/**init**.py", line 70, in start
    self._setup_api()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/pokemongo_bot/__init__.py", line 142, in _setup_api
    password=self.config.password, shared_lib=self.config.load_library)
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/api/__init__.py", line 26, in **init**
    self._api.activate_signature(shared_lib)
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

The config.json file is updated from config.json.example to reflect new attributes, I have kept encrypt.c, encrypt.o, libencrypt.so, libencrypt-darwin.so in /lib as well as /pokemongo_bot directories.

**Comment by umanghome** [comment]
Fixed it with pip install -r requirements.txt, getting a new error #218
