### ISSUE TITLE
libencrypt-darwin.so image not found

### ISSUE THREAD

**Issue by umanghome** [OpenPoGo/OpenPoGoBot#218]
### Expected Behavior

Bot should start
### Actual Behavior

libencrypt-darwin.so not found
### Other Information

OS: OS X
Git Commit: 

Traceback (most recent call last):
  File "pokecli.py", line 361, in <module>
    main()
  File "pokecli.py", line 349, in main
    bot.start()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/pokemongo_bot/**init**.py", line 70, in start
    self._setup_api()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/pokemongo_bot/__init__.py", line 147, in _setup_api
    while not self.api_wrapper.login():
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/api/__init__.py", line 31, in login
    return self._api.login(provider, username, password, app_simulation=True)
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libencrypt-darwin.so, 6): image not found

The config.json file is updated from config.json.example to reflect new attributes, I have kept encrypt.c, encrypt.o, libencrypt.so, libencrypt-darwin.so in /lib as well as /pokemongo_bot directories.

**Comment by umanghome** [comment]
Changed lib_path in pgoapi.py, getting this now:

Traceback (most recent call last):
  File "pokecli.py", line 361, in <module>
    main()
  File "pokecli.py", line 349, in main
    bot.start()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/pokemongo_bot/**init**.py", line 70, in start
    self._setup_api()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/pokemongo_bot/__init__.py", line 147, in _setup_api
    while not self.api_wrapper.login():
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/api/__init__.py", line 31, in login
    return self._api.login(provider, username, password, app_simulation=True)
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/pgoapi.py", line 211, in call
    request.activate_signature(lib_path)
  File "/Users/umanghome/MAMP/www/OpenPoGoBot/env/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/umanghome/MAMP/www/OpenPoGoBot/lib/libencrypt-darwin.so, 6): Library not loaded: libencrypt.so
  Referenced from: /Users/umanghome/MAMP/www/OpenPoGoBot/lib/libencrypt-darwin.so
  Reason: image not found

**Comment by umanghome** [comment]
Copied libencrypt-darwin.so to /
