### ISSUE TITLE
Bot crashes after pokestop cooldown

### ISSUE THREAD

**Issue by ThomasWSandberg** [OpenPoGo/OpenPoGoBot#225]
### Expected Behavior

The bot should continue finding pokestops and pokemons
### Actual Behavior

[2016-08-08 21:26:10] [x] PokemonGO Bot v1.0
[2016-08-08 21:26:10] [x] Configuration initialized
[2016-08-08 21:26:10] [Plugins] Loaded plugin "evolver".
[2016-08-08 21:26:11] [Plugins] Loaded plugin "web".
[2016-08-08 21:26:11] [Plugins] Loaded plugin "recycle_items".
[2016-08-08 21:26:11] [Plugins] Loaded plugin "catch_pokemon".
[2016-08-08 21:26:11] [Plugins] Loaded plugin "spin_pokestop".
[2016-08-08 21:26:11] [Plugins] Loaded plugin "transfer_pokemon".
[2016-08-08 21:26:11] [Plugins] Loaded plugin "egg_incubator".
[2016-08-08 21:26:12] [Plugins] Plugins loaded: ['catch_pokemon', 'egg_incubator', 'evolver', 'recycle_items', 'spin_pokestop', 'transfer_pokemon', 'web']
[2016-08-08 21:26:12] [Events] Events available: ['after_transfer_pokemon', 'bot_initialized', 'caught_pokemon', 'gyms_found', 'incubate_egg', 'inventory_update', 'item_ba
g_full', 'logging', 'player_update', 'pokemon_bag_full', 'pokemon_caught', 'pokemon_found', 'pokestop_arrived', 'pokestops_found', 'position_updated', 'set_campsite', 'tra
nsfer_pokemon', 'walking_started', 'waypoint_add', 'waypoint_remove']
[2016-08-08 21:26:12]
[2016-08-08 21:26:12] [x] Last location flag used. Overriding passed in location
[2016-08-08 21:26:12] [x] Last in-game location was set as: (40.78314836287861, -73.97104902026055, 0.0)
[2016-08-08 21:26:12]
[2016-08-08 21:26:15] [+] Login to Pokemon Go successful.
[2016-08-08 21:26:15] [#]
[2016-08-08 21:26:15] [#] Username: XxX
[2016-08-08 21:26:15] [#] Acccount Creation: 2016-08-01 20:09:04.333000
[2016-08-08 21:26:15] [#] Bag Storage: 82/350
[2016-08-08 21:26:15] [#] Pokemon Storage: 12/250
[2016-08-08 21:26:15] [#] Stardust: 2100
[2016-08-08 21:26:15] [#] Pokecoins: 0
[2016-08-08 21:26:15] [#] PokeBalls: 56
[2016-08-08 21:26:15] [#] GreatBalls: 0
[2016-08-08 21:26:15] [#] UltraBalls: 0
[2016-08-08 21:26:15] [#] -- Level: 5
[2016-08-08 21:26:15] [#] -- Experience: 11620
[2016-08-08 21:26:15] [#] -- Experience until next level: 3380
[2016-08-08 21:26:15] [#] -- Pokemon Captured: 21
[2016-08-08 21:26:15] [#] -- Pokestops Visited: 31
[2016-08-08 21:26:15] [Recycler] Recycling 6 Poke Balls
[API] Requesting too fast. Retrying in 10 seconds...
[2016-08-08 21:26:26] [Recycler] Recycling 2 Potions
[2016-08-08 21:26:27] [Recycler] Recycled 8 items.
[2016-08-08 21:26:27] [#]
[2016-08-08 21:26:27] [x] Starting PokemonGo Bot....
[2016-08-08 21:26:28] [PokeStop] Nearby PokeStop found "Caduceus Woman" (0.00km away)
[2016-08-08 21:26:28] [PokeStop] Spinning...
[2016-08-08 21:26:32] [PokeStop] Loot:
[2016-08-08 21:26:32] [PokeStop] + 50 XP
[2016-08-08 21:26:32] [PokeStop] + 1 Revive
[2016-08-08 21:26:32] [PokeStop] + 2 Poke Balls
[2016-08-08 21:26:32] [PokeStop] PokeStop is on cooldown for 5.01 minutes.
Traceback (most recent call last):
  File "pokecli.py", line 371, in <module>
    main()
  File "pokecli.py", line 364, in main
    bot.run()
  File "C:\Projects\Poke\PokomonBot\OpenPoGoBot\pokemongo_bot__init__.py", line 114, in run
    for _ in self.stepper.step(destination):
  File "C:\Projects\Poke\PokomonBot\OpenPoGoBot\pokemongo_bot\stepper.py", line 58, in step
    format_time(len(destination.steps))),
AttributeError: 'Destination' object has no attribute 'steps'
### Steps to Reproduce

Start Bot with python pokecli.py --config-json config.json, and the following config setup

{
    "auth_service": "ptc",
    "username": "USERNAME",
    "password": "PASSWORD",
    "location": "40.777629,-73.966795",
    "gmapkey": "GMAPKEY",
    "google_directions": true,
    "incubation_fill": false,
    "incubation_use_all": false,
    "incubation_priority": ["10km", "5km", "2km"],
    "incubation_restrict": {
        "2km": 901
    },
    "cp": 150,
    "max_steps": 1,
    "walk": 4,
    "initial_transfer": false,
    "recycle_items": true,
    "pokemon_potential": 0.70,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": {
        "1": { "keep": 50 },
        "101": { "keep": 10 },
        "102": { "keep": 30 },
        "103": { "keep": 30 },
        "201": { "keep": 30 },
        "701": { "keep": 100 }
    },
    "path_finder": "google",
    "navigator": "fort",
    "navigator_waypoints": [],
    "navigator_campsite": null
}
### Other Information

OS: Windows 10 (x64)
Git Commit:

**Comment by registered99** [comment]
Change `format_time(len(destination.steps))),` to `format_time(len(destination.step()))),` in stepper.py

**Comment by isukharev** [comment]
Hey, I had same problem and **solved** this just added '_' before 'steps' in file "/home/user/OpenPoGoBot/pokemongo_bot/stepper.py", line 58.
Before:
`logger.log("Walking towards {} ({} away, eta {})".format(destination.name,
                                                                     format_dist(dist, self.config.distance_unit),
                                                                     format_time(len(destination.steps))),
                       prefix="Navigation")`
Work version:
`logger.log("Walking towards {} ({} away, eta {})".format(destination.name,
                                                                     format_dist(dist, self.config.distance_unit),
                                                                     format_time(len(destination._steps))),
                       prefix="Navigation")`

**Comment by andythorne** [comment]
#227 Fixes this
