### ISSUE TITLE
Error after startup and Pokemon capture

### ISSUE THREAD

**Issue by HowieMowie** [OpenPoGo/OpenPoGoBot#231]
Expected Behavior

Expected behavior is to find, catch and proceed to next closet pokestop.

Actual Behavior

Bot starts at location specified and finds a wild evee, catches evee and doesn't transfer then fails.
[2016-08-08 16:46:48] [x] Starting PokemonGo Bot....
[2016-08-08 16:46:49] [Catch] A wild Eevee appeared! [CP 77] [Potential 0.84]
[2016-08-08 16:46:53] [Catch] Using Pokeball... (136 left!)
[2016-08-08 16:46:54] [Catch] Eevee has been caught! (CP 77, IV 0.84)
[2016-08-08 16:46:54] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-08 16:46:54] [Transfer] Transferring caught Pokemon with CP NOT above 100 and IV NOT above 0.4 and excluding [''].
[2016-08-08 16:46:54] [Transfer] No Pokemon to transfer.
[2016-08-08 16:46:54] [Transfer] Transferred 0 Pokemon.
Traceback (most recent call last):
File "pokecli.py", line 361, in 
main()
File "pokecli.py", line 354, in main
bot.run()
File "/home/howard/OpenPoGoBot/pokemongo_bot/init.py", line 109, in run
self.stepper.get_route_between(position_lat, position_lng, destination.target_lat, destination.target_lng, destination.target_alt)
File "/home/howard/OpenPoGoBot/pokemongo_bot/stepper.py", line 75, in get_route_between
path_points = self.path_finder.path(from_lat, from_lng, to_lat, to_lng)
File "/home/howard/OpenPoGoBot/pokemongo_bot/navigation/path_finder/google_path_finder.py", line 15, in path
gmaps = googlemaps.Client(key=self.config.gmapkey)
File "/home/howard/OpenPoGoBot/env/local/lib/python2.7/site-packages/googlemaps/client.py", line 108, in init
raise ValueError("Must provide API key or enterprise credentials "
ValueError: Must provide API key or enterprise credentials when creating client.

Steps to Reproduce

start OpenPoGoBot with -a ptc with user password and location coordinates.

Other Information

OS: Distributor ID: Ubuntu
Description: Ubuntu 14.04.5 LTS
Release: 14.04
Codename: trusty
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) 050d266aadc208de7656c6062b121a309bf3268f
Python Version: (run 'python -V' and paste it here) Python 2.7.6

**Comment by MaxLeiter** [comment]
you need to provide a gmaps API key (will be fixed soonish) with the -k parameter

**Comment by HowieMowie** [comment]
Never setup a gmaps API key but got one setup and it returned this error "googlemaps.exceptions.ApiError: REQUEST_DENIED (This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/directions_backend?project=_)"
I see the server key on the console but I don't see a way to authorize use of the API.

**Comment by tehp** [comment]
![image](https://cloud.githubusercontent.com/assets/3845735/17502118/2df6ff9c-5d9a-11e6-9d9a-44855223863d.png)

Is this enabled?

**Comment by AlexDevelop** [comment]
@HowieMowie if it's still relevant, you also need to add (whitelist) your external ip address.

**Comment by HowieMowie** [comment]
Started working after it was enabled.  Thank you very much.
