### ISSUE TITLE
  SubjectAltNameWarning Traceback (most recent call last):  

### ISSUE THREAD

**Issue by GucciChen** [OpenPoGo/OpenPoGoBot#238]
i have make in lib and there have libencrypt.so .
but still 
  SubjectAltNameWarning
Traceback (most recent call last):
  File "pokecli.py", line 372, in <module>
    main()
  File "pokecli.py", line 360, in main
    bot.start()
  File "/home/OpenPoGoBot/pokemongo_bot/**init**.py", line 72, in start
    self._setup_api()
  File "/home/OpenPoGoBot/pokemongo_bot/__init__.py", line 160, in _setup_api
    while not self.api_wrapper.login():
  File "/home/OpenPoGoBot/api/__init__.py", line 36, in login
    return self._api.login(provider, username, password, app_simulation=True)
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: libencrypt.so: cannot open shared object file: No such file or directory

OS: linux debian 8 
Git Commit: e60f0ea509553eea8d53760ad0f47a6cf05601e0

**Comment by nue-melexis** [comment]
I added
 "load_library": "./libencrypt.so"
to the config.json and put the libencrypt.so to bot root dir "e.g. ~/OpenPoGoBot/libencrypt.so

**Comment by GucciChen** [comment]
@nue-melexis add at where ?

**Comment by wchill** [comment]
Add it one folder up from `lib`.

**Comment by GucciChen** [comment]
@wchill i put it OpenPoGoBot/libencrypt.so
still no work .

**Comment by nue-melexis** [comment]
just add the line 
"load_library": "./libencrypt.so"
to OpenPogoBot/config.json (or where your config lies)
-alternatively specify  --load-library ./libencrypt.so on command line

put the file then directly under OpenPogoBot folder

**Comment by GucciChen** [comment]
@nue-melexis 
-alternatively specify --load-library ./libencrypt.so where is this?

**Comment by nue-melexis** [comment]
(like you start it) pokecly.py  --load-library ./libencrypt.so ...(other options)

**Comment by GucciChen** [comment]
...anthor error 
  SubjectAltNameWarning
Traceback (most recent call last):
  File "pokecli.py", line 372, in <module>
    main()
  File "pokecli.py", line 360, in main
    bot.start()
  File "/home/OpenPoGoBot/pokemongo_bot/**init**.py", line 72, in start
    self._setup_api()
  File "/home/OpenPoGoBot/pokemongo_bot/__init__.py", line 160, in _setup_api
    while not self.api_wrapper.login():
  File "/home/OpenPoGoBot/api/__init__.py", line 36, in login
    return self._api.login(provider, username, password, app_simulation=True)
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/OpenPoGoBot/src/pgoapi/pgoapi/rpc_api.py", line 332, in _parse_main_response
    raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...

**Comment by wchill** [comment]
If you're getting that error, then you're trying to run the bot on a cloud provider. Those will not work as Niantic has banned those IP ranges.

**Comment by GucciChen** [comment]
@wchill  yes ,i i used gae .....but 3day ago it's work ...

**Comment by wchill** [comment]
Yes, all cloud providers haven't worked for the past few days. This is why sites like PokeAdvisor no longer work.

**Comment by GucciChen** [comment]
@wchill all google's ip is block ?i have 3000 IP
all block ?

**Comment by GucciChen** [comment]
oh ....fuck . i was in china .....if it clock .how can i use bot ....

**Comment by wchill** [comment]
You will need to either find a VPS provider or use a system-wide proxy/VPN that is not blocked.

**Comment by GucciChen** [comment]
how can i see which IP is block ? i just delete blocked ip .will it work again ?
