### ISSUE TITLE
Module Not Found 

### ISSUE THREAD

**Issue by maaim** [OpenPoGo/OpenPoGoBot#291]
Just wondering which module I'm missing.  
### Actual Behavior

Output below:
Traceback (most recent call last):
  File "pokecli.py", line 380, in <module>
    main()
  File "pokecli.py", line 368, in main
    bot.start()
  File "C:\Users\C\Desktop\OpenPoGoBot-master\pokemongo_bot__init__.py", line 74, in start
    self._setup_api()
  File "C:\Users\C\Desktop\OpenPoGoBot-master\pokemongo_bot__init__.py", line 165, in _setup_api
    while not self.api_wrapper.login():
  File "C:\Users\C\Desktop\OpenPoGoBot-master\api__init__.py", line 36, in login
    return self._api.login(provider, username, password, app_simulation=True)
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 173, in login
    response = self.app_simulation_login()
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 150, in app_simulation_login
    response = request.call()
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 222, in call
    request.activate_signature(lib_path)
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 84, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes__init__.py", line 362, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
### Other Information

OS: Win10
Git Commit: Master

**Comment by wchill** [comment]
https://github.com/OpenPoGo/OpenPoGoBot#encrypt-shared-library

**Comment by maaim** [comment]
thank you
