### ISSUE TITLE
API Key not Taking when Running Bot 

### ISSUE THREAD

**Issue by UnKn0wN-Binary-zz** [OpenPoGo/OpenPoGoBot#323]
### Expected Behavior

Bot Should run and Spin Stops
### Actual Behavior

Bot Spins a Stop then Crashes giving an API Error on Line 108:

[2016-08-15 18:09:45] [PokeStop] + 50 XP
[2016-08-15 18:09:45] [PokeStop] + 3 Poke Balls
[2016-08-15 18:09:45] [PokeStop] PokeStop is on cooldown for 4.94 minutes.
Traceback (most recent call last):
  File "C:\Users\Root\Desktop\OpenPoGoBot-master\pokecli.py", line 380, in <modu
le>
    main()
  File "C:\Users\Root\Desktop\OpenPoGoBot-master\pokecli.py", line 373, in main
    bot.run()
  File "C:\Users\Root\Desktop\OpenPoGoBot-master\pokemongo_bot__init__.py", lin
e 118, in run
    destination.target_alt
  File "C:\Users\Root\Desktop\OpenPoGoBot-master\pokemongo_bot\stepper.py", line
 74, in get_route_between
    path_points = self.path_finder.path(from_lat, from_lng, to_lat, to_lng)
  File "C:\Users\Root\Desktop\OpenPoGoBot-master\pokemongo_bot\navigation\path_f
inder\google_path_finder.py", line 16, in path
    gmaps = googlemaps.Client(key=self.config.gmapkey)
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 108, in __init
__
    raise ValueError("Must provide API key or enterprise credentials "
ValueError: Must provide API key or enterprise credentials when creating client.
### Steps to Reproduce

Start Bot Like Normal and Try to Run 
### Other Information

OS: Win 7 
![pokego](https://cloud.githubusercontent.com/assets/21028525/17681516/3d4be0fa-6314-11e6-90b7-8abcfa40c171.PNG)

Git Commit:

**Comment by wchill** [comment]
Update to latest master as you are on an old version. You will need to update your config files accordingly.
