### ISSUE TITLE
Bug/Typo - config.yml "location" not being used inline, crashing app.

### ISSUE THREAD

**Issue by Deefjuh** [OpenPoGo/OpenPoGoBot#327]
### Expected Behaviour

Setting the location in config.yml in the option "location" should run the bot on the set location.
### Actual Behavior

When starting the application, the app crashes with a Traceback:

```
Traceback (most recent call last):
  File "pokecli.py", line 93, in <module>
    main()
  File "pokecli.py", line 81, in main
    bot.start()
  File "/home/test/OpenPoGoBot/pokemongo_bot/__init__.py", line 73, in start
    self._setup_api()
  File "/home/test/OpenPoGoBot/pokemongo_bot/__init__.py", line 158, in _setup_api
    self._set_starting_position()
  File "/home/test/OpenPoGoBot/pokemongo_bot/__init__.py", line 270, in _set_starting_position
    self._read_config_location()
  File "/home/test/OpenPoGoBot/pokemongo_bot/__init__.py", line 278, in _read_config_location
    self.position = self._get_pos_by_name(self.config["mapping"]["location_cache"])
  File "/home/test/OpenPoGoBot/pokemongo_
```

After some quick debugging the problem lies in (probably) a typo in the function " _read_config_location":

```
    def _read_config_location(self):
        self.position = self._get_pos_by_name(self.config["mapping"]["location_cache"])
        self.api_wrapper.set_position(*self.position)
        logger.log('')
        logger.log(u'[x] Address found: {}'.format(self.config["mapping"]["location_cache"]))
```

This function uses the config option "location_cache" in a function call to fetch the Google coords. As I interpret the code, it should be expecting a location string (hence the logger.log call in the end), and not a boolean.

I fixed this problem by replacing the config option with "location" instead.
This worked fine, fetched the correct Google coords and the last logger.log prints a logical message.
### Steps to Reproduce

Start the bot in a regular way, with a valid "location" string set.
### Other Information

OS: 
Git Commit:

**Comment by Deefjuh** [comment]
Sorry, jumped the gun. Did another pull and saw that the **init**.py is a lot smaller, thus making this not an issue anymore.
