### ISSUE TITLE
Cannot run bot, please help

### ISSUE THREAD

**Issue by mrkaqz** [OpenPoGo/OpenPoGoBot#330]
I am trying to run bot from raspberry pi 3 

after i got libencrypt.so on the bot root folder and run the command
this is error below:

(env) pi@raspberrypi:~/OpenPoGoBot $ python pokecli.py config/config.yml
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context  # type: ignore
AttributeError: 'module' object has no attribute '_create_unverified_context'

OS: raspbian

**Comment by niicojs** [comment]
this need a pythin rather up to date, what version are you using?
you can try to disable those lines also

**Comment by mrkaqz** [comment]
It is Python 2.7.9

**Comment by niicojs** [comment]
Did you pip install -r requirements.txt?

**Comment by mrkaqz** [comment]
Yes, I did 

Follow instruction below

git clone --recursive https://www.github.com/OpenPoGo/OpenPoGoBot
cd OpenPoGoBot
virtualenv env
source env/bin/activate
pip install -r requirements.txt

**Comment by niicojs** [comment]
Try removing lines 40 to 42 in pokecli.py

**Comment by niicojs** [comment]
did it work?

**Comment by mrkaqz** [comment]
nope, it gave another error below

---

(env) pi@raspberrypi:~/OpenPoGoBot $ python pokecli.py config/config.yml
[2016-08-17 22:41:11] [Plugins] Loaded plugin "egg_incubator".
[2016-08-17 22:41:11] [Plugins] Loaded plugin "spin_pokestop".
[2016-08-17 22:41:11] [Plugins] Loaded plugin "recycle_items".
[2016-08-17 22:41:11] [Plugins] Loaded plugin "evolver".
[2016-08-17 22:41:11] [Plugins] Loaded plugin "catch_pokemon".
[2016-08-17 22:41:11] [Plugins] Loaded plugin "transfer_pokemon".
Traceback (most recent call last):
  File "pokecli.py", line 88, in <module>
    main()
  File "pokecli.py", line 73, in main
    kernel.boot()
  File "/home/pi/OpenPoGoBot/app/kernel.py", line 66, in boot
    for plugin in self.container.get_by_tag('plugin'):
  File "/home/pi/OpenPoGoBot/app/service_container.py", line 88, in get_by_tag
    services.append(self.get(service_id))
  File "/home/pi/OpenPoGoBot/app/service_container.py", line 77, in get
    self._services[service_id] = self._make_service(service_id)
  File "/home/pi/OpenPoGoBot/app/service_container.py", line 50, in _make_service
    args.append(self.get(service_arg[1:]))
  File "/home/pi/OpenPoGoBot/app/service_container.py", line 74, in get
    raise ServiceNotFoundException('Service "{}" was not registered.'.format(service_id))
app.exceptions.ServiceNotFoundException: Service "config.egg_incubator" was not registered.

**Comment by niicojs** [comment]
did you rename all .example files in config directory to .yml files to configure the bot?

**Comment by niicojs** [comment]
Closing due to no answers. Reopen it if needed.
