### ISSUE TITLE
Cannot find PoGoAPI, Script Wrongly Named

### ISSUE THREAD

**Issue by UnKn0wN-Binary-zz** [OpenPoGo/OpenPoGoBot#339]
### Expected Behavior

Bot Starts as normal
### Actual Behavior

Bot Returns:

**C:\Users\Root\Desktop\OpenPoGoBot>pokecli.py config/config.yml
Traceback (most recent call last):
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokecli.py", line 38, in <module>
    from pokemongo_bot.bot import PokemonGoBot
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokemongo_bot__init__.py", line 6, in
 <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi**

C:\Users\Root\Desktop\OpenPoGoBot>pokecli.py config/config.yml
Traceback (most recent call last):
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokecli.py", line 38, in <module>
    from pokemongo_bot.bot import bot
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokemongo_bot__init__.py", line 6, in
 <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi

C:\Users\Root\Desktop\OpenPoGoBot>pokecli.py config/config.yml
Traceback (most recent call last):
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokecli.py", line 38, in <module>
    from pokemongo_bot.bot import bot
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokemongo_bot__init__.py", line 6, in
 <module>
    from env.src.pgoapi import PGoApi
ImportError: No module named env.src.pgoapi

C:\Users\Root\Desktop\OpenPoGoBot>pokecli.py config/config.yml
Traceback (most recent call last):
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokecli.py", line 38, in <module>
    from pokemongo_bot.bot import bot
  File "C:\Users\Root\Desktop\OpenPoGoBot\pokemongo_bot__init__.py", line 6, in
 <module>
    from env.src.pgoapi.pgoapi import PGoApi
ImportError: No module named env.src.pgoapi.pgoapi

C:\Users\Root\Desktop\OpenPoGoBot>

I tried to change the file name to the correct filename but it would not work. 

Current Path is: OpenPoGoBot\env\src\pgoapi\pgoapi
### Steps to Reproduce

Download Current Build
### Other Information

OS: win7
Git Commit:

**Comment by UnKn0wN-Binary-zz** [comment]
Also I downloaded the Bot Using the Instructions and Git Bash to download. Changed all Config Files in the Config Folder and have added the encrypt.dll to my main PoGoBot folder.

**Comment by UnKn0wN-Binary-zz** [comment]
![pogobot](https://cloud.githubusercontent.com/assets/21028525/17756047/85070904-64ab-11e6-8bf8-ffcf3d972321.PNG)

**Comment by OhJayGee** [comment]
did you do 'pip install -r requirements.txt' after the download?
as in: 
git clone --recursive https://www.github.com/OpenPoGo/OpenPoGoBot
cd OpenPoGoBot
virtualenv env
source env/bin/activate
pip install -r requirements.txt

also have protobuf3 installed before?

and then run with 'python2 pokecli.py config/config.yml 
(and also have the config files in config/plugins/ renamed to .yml ?)

**Comment by UnKn0wN-Binary-zz** [comment]
I did do the-r requirements. 
I didn't run with python2 only python so I will try that. 
Yes I have protobuf3 installed. 
Changed all of the configuration files but I will double check.

**Comment by UnKn0wN-Binary-zz** [comment]
$ python pokecli.py config/config.yml
Traceback (most recent call last):
  File "pokecli.py", line 88, in <module>
    main()
  File "pokecli.py", line 73, in main
    kernel.boot()
  File "C:\Users\Root\Desktop\OpenPoGoBot\app\kernel.py", line 55, in boot
    self.load_config()
  File "C:\Users\Root\Desktop\OpenPoGoBot\app\kernel.py", line 32, in load_config
    self._configs['core'] = ruamel.yaml.load(config_file.read(), ruamel.yaml.RoundTripLoader)
  File "C:\Users\Root\Desktop\OpenPoGoBot\env\lib\site-packages\ruamel\yaml\main.py", line 75, in load
    return loader.get_single_data()
  File "C:\Users\Root\Desktop\OpenPoGoBot\env\lib\site-packages\ruamel\yaml\constructor.py", line 62, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Root\Desktop\OpenPoGoBot\env\lib\site-packages\ruamel\yaml\constructor.py", line 66, in construct_document
    data = self.construct_object(node)
  File "C:\Users\Root\Desktop\OpenPoGoBot\env\lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_object
    data = next(generator)
  File "C:\Users\Root\Desktop\OpenPoGoBot\env\lib\site-packages\ruamel\yaml\constructor.py", line 1042, in construct_yaml_map
    data = CommentedMap()
  File "c:\python27\Lib\collections.py", line 48, in __init__
    self.update(_args, *_kwds)
TypeError: update() takes exactly 2 arguments (1 given)
(env)

**Comment by UnKn0wN-Binary-zz** [comment]
Brand New Install with the above configurations completed.

**Comment by keroy** [comment]
you're not loading in the virtualenv environment. 
source env/bin/activate <--- you'll need to call this

**Comment by UnKn0wN-Binary-zz** [comment]
How would I go about calling it, I ran the command and it says below:

(Env)

That's all, do I need to call it in every bot run?

**Comment by UnKn0wN-Binary-zz** [comment]
Also source env/bin/activate is not a valid Path. The Path I have is:

C:\Users\Root\Desktop\OpenPoGoBot\env\Scripts

![image](https://cloud.githubusercontent.com/assets/21028525/17825936/17bf8bc4-663a-11e6-8c35-a97f67a9145d.png)

**Comment by UnKn0wN-Binary-zz** [comment]
So, Did a Brand new install on a Virtual Box, Installed everything as aboe and in the install, changed all of the configs and now I get this: 

 python pokecli.py config/config.yml
Traceback (most recent call last):
  File "pokecli.py", line 88, in <module>
    main()
  File "pokecli.py", line 73, in main
    kernel.boot()
  File "C:\Users\root\Desktop\OpenPoGoBot\app\kernel.py", line 55, in boot
    self.load_config()
  File "C:\Users\root\Desktop\OpenPoGoBot\app\kernel.py", line 39, in load_config
    for node in os.listdir(os.path.join(config_dir, plugin_config_dir)):
WindowsError: [Error 3] The system cannot find the path specified: 'config\c/_._'

**Comment by bornbygoogle** [comment]
Change the last line in the config.yml, i had same prob. Double check the last line config.yml.example and your config file, you'll see the difference.

**Comment by UnKn0wN-Binary-zz** [comment]
YOu are awesome, I don't know why the New Pull wouldn't update that, appreciate all of the help.
