### ISSUE TITLE
Bot Doesn't Start

### ISSUE THREAD

**Issue by oralunal** [OpenPoGo/OpenPoGoBot#349]
### Expected Behavior

Bot works
### Actual Behavior

Bot throws this error:

```
(env) C:\Users\oralu\Desktop\pogo\OpenPoGoBot>python pokecli.py config/config.yml
[2016-08-22 01:27:39] [Plugins] Loaded plugin "evolver".
[2016-08-22 01:27:40] [Plugins] Loaded plugin "socket".
[2016-08-22 01:27:40] [Plugins] Loaded plugin "recycle_items".
[2016-08-22 01:27:40] [Plugins] Loaded plugin "collect_rewards".
[2016-08-22 01:27:40] [Plugins] Loaded plugin "catch_pokemon".
[2016-08-22 01:27:40] [Plugins] Loaded plugin "spin_pokestop".
[2016-08-22 01:27:40] [Plugins] Loaded plugin "transfer_pokemon".
[2016-08-22 01:27:40] [Plugins] Loaded plugin "egg_incubator".
[2016-08-22 01:27:40] [x] PokemonGO Bot v1.0
[2016-08-22 01:27:40] [x] Configuration initialized
[2016-08-22 01:27:40] [Socket] Starting socket server...
[2016-08-22 01:27:41]
[2016-08-22 01:27:41] [x] Address found: 35.625855208465275,139.88125562667847
[2016-08-22 01:27:41] [x] Position in-game set as: (35.625855208465275, 139.88125562667847, 9.40514087677002)
[2016-08-22 01:27:41]
Traceback (most recent call last):
  File "pokecli.py", line 88, in <module>
    main()
  File "pokecli.py", line 77, in main
    bot.start()
  File "C:\Users\oralu\Desktop\pogo\OpenPoGoBot\pokemongo_bot\bot.py", line 59, in start
    self._setup_api()
  File "C:\Users\oralu\Desktop\pogo\OpenPoGoBot\pokemongo_bot\bot.py", line 91, in _setup_api
    while not self.player_service.login():
  File "C:\Users\oralu\Desktop\pogo\OpenPoGoBot\pokemongo_bot\service\player.py", line 28, in login
    self._logged_in = self._api_wrapper.login()
  File "C:\Users\oralu\Desktop\pogo\OpenPoGoBot\api\__init__.py", line 37, in login
    return self._api.login(provider, username, password, app_simulation=True)
  File "c:\users\oralu\desktop\pogo\openpogobot\env\src\pgoapi\pgoapi\pgoapi.py", line 175, in login
    response = self.app_simulation_login()
  File "c:\users\oralu\desktop\pogo\openpogobot\env\src\pgoapi\pgoapi\pgoapi.py", line 152, in app_simulation_login
    response = request.call()
  File "c:\users\oralu\desktop\pogo\openpogobot\env\src\pgoapi\pgoapi\pgoapi.py", line 222, in call
    request.activate_signature(lib_path)
  File "c:\users\oralu\desktop\pogo\openpogobot\env\src\pgoapi\pgoapi\rpc_api.py", line 81, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\Lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\Lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 geerli bir Win32 uygulamas² de­il
```
### Other Information

OS: Win 10
Git Commit:

**Comment by wchill** [comment]
Your `encrypt.dll` is the wrong machine word size. You might be trying a 32-bit dll on a 64-bit python installation or vice versa.

**Comment by oralunal** [comment]
I couldn't configure how to install this bot, it really sucks. Build DLL.bat not working because of cmd doesn't run "CL" command. I tried with Visual C++ 2008 Command Prompt but error while compiling "stdint.h". I searched a little and found that I have to use Visual Studio 2012...

Thank you guys but I'm not gonna use this or install :) It's over me :)

**Comment by wchill** [comment]
You can find a 64-bit version of encrypt.dll floating around the internet if you search carefully enough. We just can't distribute it ourselves due to copyright.
