### ISSUE TITLE
utf8' codec can't decode byte #xc5: invalid continuation byte   in "<byte string>", position 1621

### ISSUE THREAD

**Issue by stvnmbr1** [OpenPoGo/OpenPoGoBot#354]
OS: Debian 8

Hi guys !

awesome work to keep everything going to help out catching pokemons ;)
Sadly i can't get it to work :( I thought its something with pip but i reinstalled everything but to no avail.. Looks like the bot isn't even starting because of the error that comes first..

any help would be great !

/pokecli.py config/config.yml --debug

gives me

```
Traceback (most recent call last):
  File "./pokecli.py", line 88, in <module>
    main()
  File "./pokecli.py", line 73, in main
    kernel.boot()
  File "/home/anon/PokemonGo-Bot/web/OpenPoGoBot/app/kernel.py", line 55, in boot
    self.load_config()
  File "/home/anon/PokemonGo-Bot/web/OpenPoGoBot/app/kernel.py", line 32, in load_config
    self._configs['core'] = ruamel.yaml.load(config_file.read(), ruamel.yaml.RoundTripLoader)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/reader.py", line 92, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/reader.py", line 149, in determine_encoding
    self.update(1)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/reader.py", line 185, in update
    exc.encoding, exc.reason)
ruamel.yaml.reader.ReaderError: 'utf8' codec can't decode byte #xc5: invalid continuation byte
  in "<byte string>", position 1621
```

is this an issue with locales? I already looked through the issues but i can't find a fix..

**Comment by wchill** [comment]
Can you show me your `config.yml`?

**Comment by stvnmbr1** [comment]
```
debug: false
load_library: "libencrypt.so"

login:
    # Choose whether to login using Google (google) or Pokemon Trainer Club (ptc)
    auth_service: "google"

    # Should be self explanatory
    username: "filled in"
    password: "filled in"

mapping:
    # Required, see https://developers.google.com/maps/documentation/javascript/get-api-key for details
    gmapkey: "filled in"

    # Can be a string or a set of GPS coordinates
    location: "-33.860109, 151.2131920"

    # Use last known location instead of above specified location
    location_cache: true

    # Specify what units  for distance the bot should use
    distance_unit: "km"

    # The radius (in meters) to fetch cell data for. Cell data includes pokestops and nearby pokemon
    # Max value is 1500
    cell_radius: 500

movement:
    # Use Google Maps Direction API (google) or just walk directly (direct)
    path_finder: "google"

    # Select which navigation method to use
    # fort: Navigate to nearby PokeStops
    # waypoint: Navigate to a list of waypoints
    # camper: Camp at one spot
    navigator: "fort"

    # Only required if using waypoint navigator; specify which waypoints to visit
    navigator_waypoints: []

    # Only required if using camping navigator; specify where to camp
    navigator_campsite: null

    # Specify how fast the bot should walk, in meters/second
    walk_speed: 4.16

plugins:
    # Do not automatically load the specified plugins
    exclude: []

    # Plugin directories to load
    include:
        - ./plugins

    # Load plugin YAML config files from these directories, relative to the main config file directory.
    # Later directories will override configs in previous directories.
    config:
        - "plugins"
```
