### ISSUE TITLE
Service "config.evolve_pokemon" was not registered

### ISSUE THREAD

**Issue by testbotpokemon123456** [OpenPoGo/OpenPoGoBot#363]
```

(env) C:\Users\xxxxx\Desktop\test\OpenPoGoBot>python pokecli.py config/config.yml
[2017-03-16 19:05:11] [Plugins] Loaded plugin "evolver".
[2017-03-16 19:05:14] [Plugins] Loaded plugin "socket".
[2017-03-16 19:05:14] [Plugins] Loaded plugin "recycle_items".
[2017-03-16 19:05:14] [Plugins] Loaded plugin "collect_rewards".
[2017-03-16 19:05:14] [Plugins] Loaded plugin "catch_pokemon".
[2017-03-16 19:05:14] [Plugins] Loaded plugin "spin_pokestop".
[2017-03-16 19:05:14] [Plugins] Loaded plugin "transfer_pokemon".
[2017-03-16 19:05:14] [Plugins] Loaded plugin "egg_incubator".
Traceback (most recent call last):
  File "pokecli.py", line 88, in <module>
    main()
  File "pokecli.py", line 73, in main
    kernel.boot()
  File "C:\Users\xxxxx\Desktop\test\OpenPoGoBot\app\kernel.py", line 67, in boot
    for plugin in self.container.get_by_tag('plugin'):
  File "C:\Users\xxxxx\Desktop\test\OpenPoGoBot\app\service_container.py", line 88, in get_by_tag
    services.append(self.get(service_id))
  File "C:\Users\xxxxx\Desktop\test\OpenPoGoBot\app\service_container.py", line 77, in get
    self._services[service_id] = self._make_service(service_id)
  File "C:\Users\xxxxx\Desktop\test\OpenPoGoBot\app\service_container.py", line 50, in _make_service
    args.append(self.get(service_arg[1:]))
  File "C:\Users\xxxxx\Desktop\test\OpenPoGoBot\app\service_container.py", line 74, in get
    raise ServiceNotFoundException('Service "{}" was not registered.'.format(service_id))
app.exceptions.ServiceNotFoundException: Service "config.evolve_pokemon" was not registered.
```
How can i fix it ?

**Comment by wchill** [comment]
This bot is no longer maintained.
