### ISSUE TITLE
Ignore list not working

### ISSUE THREAD

**Issue by fonix232** [OpenPoGo/OpenPoGoBot#59]
### Expected Behavior

After adding ./data/catch-ignore.yml, the bot should run fine and ignore the pokemons listed
### Actual Behavior

The bot crashes with the following error:

`[2016-07-25 14:54:26] [x] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "pokecli.py", line 182, in <module>
    main()
  File "pokecli.py", line 173, in main
    bot.take_step()
  File "d:\pokemon\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 40, in take_step
    self.stepper.take_step()
  File "d:\pokemon\Bot\PokemonGo-Bot\pokemongo_bot\stepper.py", line 40, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "d:\pokemon\Bot\PokemonGo-Bot\pokemongo_bot\stepper.py", line 101, in _work_at_position
    self.bot.work_on_cell(map_cells, position, pokemon_only)
  File "d:\pokemon\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 43, in work_on_cell
    self._remove_ignored_pokemon(map_cells)
  File "d:\pokemon\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 68, in _remove_ignored_pokemon
    if pokemon_name in ignores:
NameError: global name 'ignores' is not defined`
### Steps to Reproduce
1. Add ./data/catch-ignore.yml
2. Add the sample content to it
3. Run the bot
### Other Information

OS: Windows 10
Git Commit: 65f0fb8

**Comment by wchill** [comment]
Should have been fixed in #40. Please update your repository and try again.

**Comment by wangx173** [comment]
I think Ignore list is still not working

**Comment by Rlewisrlou666** [comment]
ignore list not working for me either

**Comment by Rlewisrlou666** [comment]
I downloaded Atom and used that to create the catch-ignore.yml file and I'm trying to log back in to test if it worked.
