### ISSUE TITLE
Force exit upon arriving at Pokestop

### ISSUE THREAD

**Issue by pokemon-masterbater** [OpenPoGo/OpenPoGoBot#99]
Upon arriving at a Pokestop I will get 

---

[2016-07-27 16:19:45] [#] Finished walking
[2016-07-27 16:19:45] [#] Arrived at Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 240, in <module>
    main()
  File "pokecli.py", line 233, in main
    bot.take_step()
  File "/home/frank/newshit/OpenPoGoBot-master/pokemongo_bot/**init**.py", line 65, in take_step
    self.stepper.take_step()
  File "/home/frank/newshit/OpenPoGoBot-master/pokemongo_bot/stepper.py", line 39, in take_step
    self._work_at_position(position[0], position[1], True)
  File "/home/frank/newshit/OpenPoGoBot-master/pokemongo_bot/stepper.py", line 107, in _work_at_position
    self.bot.work_on_cell(cell, pokemon_only)
  File "/home/frank/newshit/OpenPoGoBot-master/pokemongo_bot/__init__.py", line 104, in work_on_cell
    walk_worker.work()
  File "/home/frank/newshit/OpenPoGoBot-master/pokemongo_bot/cell_workers/walk_towards_fort_worker.py", line 49, in work
    logger.log(u"[#] Now at Pokestop: " + fort_name)
  File "/home/frank/newshit/OpenPoGoBot-master/pokemongo_bot/logger.py", line 29, in log
    print(output)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 43-46: ordinal not in range(256)

**Comment by wchill** [comment]
Does this happen on latest commit?

**Comment by pokemon-masterbater** [comment]
Yes I am using the latests commit and get a force exit each time I arrive at a Pokestop

**Comment by wchill** [comment]
Please provide the GPS coordinates of the PokeStop so I can check.

**Comment by pokemon-masterbater** [comment]
35.689393, 139.691436

**Comment by wchill** [comment]
I can't reproduce it. It seems like things are working properly.
For example:
`[2016-07-27 14:48:19] [#] Now at Pokestop: 東京都議会議事堂`

**Comment by kazyka** [comment]
How long did the bot run before it happened?

**Comment by pokemon-masterbater** [comment]
It literally ran all of 30 seconds maybe. 
As soon as it gets to any Pokestop it produces this error.

**Comment by MaxLeiter** [comment]
What OS and Python version are you using?

**Comment by pokemon-masterbater** [comment]
OS: Debian Linux 8 
Kernel: 3.16.0-4-amd64 on x86_64

**Comment by MaxLeiter** [comment]
What python version?

**Comment by pokemon-masterbater** [comment]
Python 2.7.9

**Comment by pokemon-masterbater** [comment]
Any ideas on how to solve this?

**Comment by epicblood** [comment]
@pokemon-masterbater try this branch and tell me if it works, I am unable to duplicate the error, but this may fix it:
https://github.com/epicblood/OpenPoGoBot/tree/patch-4

**Comment by pokemon-masterbater** [comment]
@epicblood I definitely appreciate your help with this error.
I am still receiving the same situation after using your tree though.

---

[2016-07-28 06:54:57] [#] Walking from (35.6894875, 139.6917064) to (35.689393, 139.691436) for approx. 18.00 seconds  
[2016-07-28 06:55:35] [#] Finished walking  
[2016-07-28 06:55:35] [#] Arrived at Pokestop  
Traceback (most recent call last):  
  File "pokecli.py", line 240, in <module>  
    main()  
  File "pokecli.py", line 233, in main  
    bot.take_step()  
  File "/home/frank/newshit/OpenPoGoBot-patch-4/pokemongo_bot/**init**.py", line 65, in take_step  
    self.stepper.take_step()  
  File "/home/frank/newshit/OpenPoGoBot-patch-4/pokemongo_bot/stepper.py", line 39, in take_step  
    self._work_at_position(position[0], position[1], True)  
  File "/home/frank/newshit/OpenPoGoBot-patch-4/pokemongo_bot/stepper.py", line 107, in _work_at_position  
    self.bot.work_on_cell(cell, pokemon_only)  
  File "/home/frank/newshit/OpenPoGoBot-patch-4/pokemongo_bot/__init__.py", line 104, in work_on_cell  
    walk_worker.work()  
  File "/home/frank/newshit/OpenPoGoBot-patch-4/pokemongo_bot/cell_workers/walk_towards_fort_worker.py", line 50, in work  
    logger.log(u"[#] Now at Pokestop: " + fort_name)  
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by epicblood** [comment]
@pokemon-masterbater make sure you are on the `patch-4` branch (git checkout patch-4)

**Comment by pokemon-masterbater** [comment]
I was able to fix the error by changing line 48 on "walk_towards_fort_worker.py" to

fort_name = fort_details.get("name").encode('ascii', 'ignore') if fort_details.get("name").encode('ascii', 'ignore') else "Unknown"

**Comment by epicblood** [comment]
@pokemon-masterbater try changing to 'utf-8' as opposed to 'ascii'

**Comment by fonix232** [comment]
There was a change lately to charmap codec, however it still fails for me with this:

`UnicodeEncodeError: 'charmap' codec can't encode character u'\u0171' in position 59: character maps to <undefined>`
